name: Sync Development to Main

on:
  push:
    branches:
      - development

permissions:
  contents: write

jobs:
  call-sync-development-to-main:
    uses: ./.github/workflows/sync-development-to-main.yml
    secrets: inherit